### ISSUE TITLE
Feature Request : macro spaces diff

### ISSUE THREAD

**Issue by fred-r** [ProSurfer73/Macro-Parser#10]
Support new command:

> spacediff my_space1 my_space2 my_space3
       my_space 1  |  my_space2  | my_space3
A :        0x01        |     0x30         | undefined
B:         0x02        |     0x40         | 255
C:         0x03        | undefined    |  0
D:    undefined    | undefined    |  312

The default ordering is by alphanumerical order.

**Comment by ProSurfer73** [comment]
The command is implemented. It lists only the macros that are common in all the spaces listed.
