### ISSUE TITLE
Feature request : can we have a locate command ?

### ISSUE THREAD

**Issue by fred-r** [ProSurfer73/Macro-Parser#22]
```
> locate <macrospace> TOTO

TOTO is declared in c:\defs.h
```

It would be good to avoid consuming too much memory for this.
Maybe a collection of file paths is required.
Then ,each define of the namespace refers only to this and does not recopy the full path.

**Comment by ProSurfer73** [comment]
we already have the command **where** for that.
This feature would be an expansion of the command where to macrospaces.
Nevertheless, storage filepath in memory without recopying full path would be an interesting feature.

**Comment by ProSurfer73** [comment]
Please look at the where command, it now works with macrospaces.
