### ISSUE TITLE
Too fast to be true : do you import subfolders as well ?

### ISSUE THREAD

**Issue by fred-r** [ProSurfer73/Macro-Parser#26]
![image](https://user-images.githubusercontent.com/8255133/189183027-f701a6a7-2a3e-4c82-9d57-32b5b86ca31a.png)

**Comment by ProSurfer73** [comment]
![image](https://user-images.githubusercontent.com/56694323/190242442-17e2cb05-8149-4f70-84b0-daade1758e57.png)
Yes fred all subfolders are imported.
The code has been tested many times.
There is no issue here, but thanks for mentioning a potential problem.
