### ISSUE TITLE
double-clicking on .exe does not work

### ISSUE THREAD

**Issue by fred-r** [ProSurfer73/Macro-Parser#5]
README says:
   Go to the release page.
   Download the latest stable version.
   Double-click on the executable and you're done !

But I need to run the tool in MinGW.
By double-clicking I get the following error (see snapshot):

![image](https://user-images.githubusercontent.com/8255133/188392646-9c5b0e55-124e-4ae0-a814-a956cab6e5ac.png)

**Comment by ProSurfer73** [comment]
Hi Fred.
Thanks for reporting this critical issue.
I will correct it as soon as possible.

**Comment by ProSurfer73** [comment]
I now compile the binary statically to avoid .dll issues.
