### ISSUE TITLE
Feature Request : support several macro spaces

### ISSUE THREAD

**Issue by fred-r** [ProSurfer73/Macro-Parser#8]
In the current version, all macros go in the same defines space.
I would like to define several macros spaces.

Something like:

> importfolder c:\Temp1 my_space1 : my_space_1 created if it does not exist
> importfolder c:\Temp2 my_space2 : my_space_2 created if it does not exist

Then I can do evaluations in each macros space.

Also, I'd like to add elements into an existing space:
> importfile c:\Temp3\foo.h my_space1
> importfolder c:\Temp4\ my_space1

Then for each command I indicate in which macros space I work.

Of course we need extra commands:

> list spaces
my_space1 
my_space2

> printsources my_space1
c:\Temp1
c:\Temp3\foo.h
c:\Temp4

> printsources my_space2
c:\Temp2

**Comment by ProSurfer73** [comment]
The feature is currently implemented on the main branch.

**Comment by ProSurfer73** [comment]
This feature has been released in v1.4.0 .
